package session

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"
)

// sessionsDir is where session files live, relative to the working
// directory: Forcefield stores project conversations inside the project.
const sessionsDir = ".forcefield/sessions"

// maxIDLen bounds how long a session ID may be. Real IDs are UUIDs (36
// chars); the cap keeps a hostile ID from creating absurd file names.
const maxIDLen = 128

// New creates an empty session with a unique ID.
func New() *Session {
	now := time.Now()

	return &Session{
		ID:        uuid.NewString(),
		CreatedAt: now,
		UpdatedAt: now,
		Messages:  []Message{},
	}
}

// validID reports whether id is a safe on-disk session identifier. IDs
// are normally UUIDs generated by New, but Load and Save also receive
// values that came from disk, CLI flags, or pickers, so every entry point
// validates: an ID containing path separators or dot segments could
// otherwise read or write files outside the sessions directory.
func validID(id string) bool {
	if id == "" || len(id) > maxIDLen {
		return false
	}
	if strings.ContainsAny(id, `/\`) {
		return false
	}
	switch id {
	case ".", "..":
		return false
	}
	return true
}

// Save persists the session to its JSON file.
//
// The write is atomic: the data lands in a temporary file in the same
// directory which is then renamed over the real one, so a crash or kill
// mid-write can never leave a truncated half-session behind - readers see
// either the previous complete file or the new complete file. The
// temporary file is flushed to disk before the rename so an OS-level
// crash doesn't produce an empty replacement either.
func (s *Session) Save() error {
	if !validID(s.ID) {
		return fmt.Errorf("save session: invalid session id %q", s.ID)
	}

	s.UpdatedAt = time.Now()

	dir := filepath.Join(".", filepath.FromSlash(sessionsDir))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create sessions directory: %w", err)
	}

	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return fmt.Errorf("encode session %s: %w", s.ID, err)
	}

	tmp, err := os.CreateTemp(dir, s.ID+".json.tmp-*")
	if err != nil {
		return fmt.Errorf("create temp file for session %s: %w", s.ID, err)
	}
	tmpName := tmp.Name()
	defer func() {
		// After a successful rename this is a no-op (the name is gone);
		// after any failure it removes the partial file so no debris is
		// left in the sessions directory.
		_ = os.Remove(tmpName)
	}()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("write session %s: %w", s.ID, err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("flush session %s: %w", s.ID, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close session %s: %w", s.ID, err)
	}

	path := filepath.Join(dir, s.ID+".json")
	if err := replaceFile(tmpName, path); err != nil {
		return fmt.Errorf("replace session file %s: %w", path, err)
	}
	return nil
}

// renameAttempts bounds how many times replaceFile retries the final
// rename before giving up.
const renameAttempts = 5

// replaceFile atomically replaces dst with src via rename.
//
// On Windows, renaming over a file that any thread or process still has
// open fails with a transient "Access is denied" (the destination handle
// hasn't been fully released yet - commonly antivirus, search indexing,
// or another in-flight save of the same session). A short bounded retry
// turns those spurious failures into success instead of surfacing them as
// scary save errors; on Unix the first attempt simply always succeeds and
// the loop costs nothing.
func replaceFile(src, dst string) error {
	var err error
	for attempt := 0; attempt < renameAttempts; attempt++ {
		if attempt > 0 {
			time.Sleep(time.Duration(attempt) * 5 * time.Millisecond)
		}
		if err = os.Rename(src, dst); err == nil {
			return nil
		}
	}
	return err
}

// AddMessage appends a message and updates UpdatedAt.
func (s *Session) AddMessage(role, content string) {
	s.Messages = append(s.Messages, Message{
		Role:    role,
		Content: content,
		Time:    time.Now(),
	})

	s.UpdatedAt = time.Now()
}

// Load reads a session by ID.
//
// A malformed session file is never rewritten or deleted here: Load
// reports the problem and leaves the data untouched so the user (or a
// future repair flow) can decide what happens to it.
func Load(id string) (*Session, error) {
	if !validID(id) {
		return nil, fmt.Errorf("load session: invalid session id %q", id)
	}

	path := filepath.Join(".", filepath.FromSlash(sessionsDir), id+".json")

	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, fmt.Errorf("no saved session with id %s", id)
		}
		return nil, fmt.Errorf("read session file %s: %w", path, err)
	}

	var s Session
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, fmt.Errorf(
			"session file %s is corrupted (%v); the file was left unchanged - delete it if you don't need it",
			path, err,
		)
	}

	// Tolerate hand-written or legacy files whose JSON body lacks an id:
	// the filename is the authoritative source for which session this is.
	if s.ID == "" {
		s.ID = id
	}

	return &s, nil
}

// Corruption describes a session file that exists on disk but could not
// be parsed. Forcefield never deletes these on its own.
type Corruption struct {
	Path string
	Err  error
}

// Error satisfies the error interface so individual corruptions can be
// reported directly.
func (c Corruption) Error() string {
	return fmt.Sprintf("%s: %v", c.Path, c.Err)
}

// List reads all saved sessions, most useful first is the caller's job.
//
// One corrupted or unreadable file does not fail the whole listing: the
// healthy sessions are still returned, and each unreadable file is
// reported through ListCorrupt so callers can surface exactly what was
// skipped instead of silently losing sessions. An error is returned only
// when the sessions directory itself cannot be read.
func List() ([]Session, error) {
	sessions, _, err := ListCorrupt()
	return sessions, err
}

// ListCorrupt is List plus the list of files that were skipped because
// they could not be read or parsed.
func ListCorrupt() ([]Session, []Corruption, error) {
	dir := filepath.Join(".", filepath.FromSlash(sessionsDir))

	files, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return []Session{}, nil, nil
	} else if err != nil {
		return nil, nil, fmt.Errorf("list sessions directory %s: %w", dir, err)
	}

	sessions := make([]Session, 0)
	var corrupt []Corruption

	for _, file := range files {
		if file.IsDir() || filepath.Ext(file.Name()) != ".json" {
			continue
		}

		path := filepath.Join(dir, file.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			corrupt = append(corrupt, Corruption{Path: path, Err: err})
			continue
		}

		var s Session
		if err := json.Unmarshal(data, &s); err != nil {
			corrupt = append(corrupt, Corruption{
				Path: path,
				Err:  fmt.Errorf("not a valid session file: %v", err),
			})
			continue
		}

		sessions = append(sessions, s)
	}

	return sessions, corrupt, nil
}
